-- 운영/로그/FAQ/사용자/리뷰/문의
DROP TABLE admin_alert CASCADE CONSTRAINTS;
DROP TABLE access_log CASCADE CONSTRAINTS;
DROP TABLE test_result CASCADE CONSTRAINTS;
DROP TABLE faq_board CASCADE CONSTRAINTS;
DROP TABLE bnk_user CASCADE CONSTRAINTS;
DROP TABLE bnk_corp_user CASCADE CONSTRAINTS;
DROP TABLE qna_board CASCADE CONSTRAINTS;
DROP TABLE review CASCADE CONSTRAINTS;

-- 문서
DROP TABLE bnk_document CASCADE CONSTRAINTS;

-- 카드 및 카테고리
DROP TABLE card_subcategory CASCADE CONSTRAINTS;
DROP TABLE card CASCADE CONSTRAINTS;
DROP TABLE card_category_rel CASCADE CONSTRAINTS;

-- 카드 진행/승인 요청 및 상세
DROP TABLE card_approval_request CASCADE CONSTRAINTS;
DROP TABLE card_approval_request_detail CASCADE CONSTRAINTS;
DROP TABLE approval_request CASCADE CONSTRAINTS;
DROP TABLE approval_request_detail CASCADE CONSTRAINTS;

-- 예적금 상품
DROP TABLE deposit_product CASCADE CONSTRAINTS;